version: '3.3'
services:
  web:
    build:
      context: /home/docker/sfmapp
      dockerfile: Dockerfile
    container_name: php_apache
    depends_on:
      - db
    ports:
      - 4000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306
